/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Leo' at '2015.02.21. 16:33' with Gradle 2.2.1
 *
 * @author Leo, @date 2015.02.21. 16:33
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
